{% set name = "optimum" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/huggingface/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ce82abe0a8c86790d05fc18b8dd2fa3b35c1049886c894a1dfb44967307bda7d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - optimum-cli = optimum.commands.optimum_cli:main
  # https://github.com/AnacondaRecipes/torchvision-feedstock/blob/master/recipe/meta.yaml#L46
  # torchvision python 3.13 support will be introduced in v 0.21, see here https://github.com/pytorch/vision/issues/8730#issuecomment-2504291914
  skip: true  # [py<39 or py>312]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - transformers >=4.29
    - pytorch >=1.11
    - packaging
    - numpy
    - huggingface_hub >=0.8.0
  run_contrained:
    - optimum-habana >=1.17.0
    - optimum-intel >=1.23.0
    - optimum-quanto >=0.2.4

# E   ModuleNotFoundError: No module named 'optimum.exporters.onnx'
# The optimum.exporters.onnx folder is not in the release tarball
{% set ignore_tests = " --ignore=tests/exporters/common/test_tasks_manager.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/pipelines/test_pipelines.py" %}
# E   FileNotFoundError: [Errno 2] No such file or directory: optimum/commands/register/cli_with_custom_command.py
{% set deselect_tests = " --deselect=tests/cli/test_cli.py::TestCLI::test_export_commands" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/cli/test_cli.py::TestCLI::test_register_command" %}
# raise ValueError(f'mutable default {type(f.default)} for field '
# E   ValueError: mutable default <class 'slice'> for field index is not allowed: use default_factory
# Python 3.11 changed dataclass validation to strictly forbid mutable defaults (including slice objects)
{% set ignore_tests = deselect_tests + " --ignore=tests/fx/parallelization/test_tensor_parallel.py" %}  # [py==311]

test:
  source_files:
    - tests
  imports:
    - optimum
  commands:
    - pip check
    - optimum-cli --help
    - pytest -v tests {{ ignore_tests }} {{ deselect_tests }}
  requires:
    - pip
    - pytest
    - parameterized
    - torchvision
    - pillow

about:
  home: https://github.com/huggingface/optimum
  summary: |
    🤗 Optimum is an extension of 🤗 Transformers and Diffusers, providing a set of 
    optimization tools enabling maximum efficiency to train and run models on targeted hardware, 
    while keeping things easy to use.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  description: |
    🤗 Optimum is an extension of Transformers that provides a set of performance optimization tools to train and run models on targeted hardware with maximum efficiency.
    The AI ecosystem evolves quickly, and more and more specialized hardware along with their own optimizations are emerging every day. 
    As such, Optimum enables developers to efficiently use any of these platforms with the same ease inherent to Transformers.
  doc_url: https://huggingface.co/docs/optimum/index
  dev_url: https://github.com/huggingface/optimum

extra:
  recipe-maintainers:
    - sugatoray
