{% set name = "optimum" %}
{% set version = "1.18.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c962cc02d55d698461cbc2e3fcf5522fab83ed846c3f904f5bed3efdc48a702b

build:
  number: 0
  # Dropping ppc because of various pytorch build issues
  skip: true  # [py<37 or (linux and ppc64le)]
  script:
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - optimum-cli = optimum.commands.optimum_cli:main

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - coloredlogs
    - sympy
    - transformers >=4.26.0,<4.40.0
    # transformers[sentencepiece] contains sentencepiece and protobuf, see https://github.com/huggingface/transformers/blob/v4.32.1/setup.py#L299
    - sentencepiece >=0.1.91,!=0.1.92
    - protobuf
    - pytorch >=1.11
    - packaging
    - numpy
    - huggingface_hub >=0.8.0
    - datasets
  run_contrained:
    - onnxruntime >=1.11.0
    - datasets >=1.2.1
    - protobuf >=3.20.1
    - onnxruntime-gpu>=1.11.0

test:
  imports:
    - optimum
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/huggingface/optimum
  summary: |
    🤗 Optimum is an extension of 🤗 Transformers and Diffusers, providing a set of 
    optimization tools enabling maximum efficiency to train and run models on targeted hardware, 
    while keeping things easy to use.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  description: |
    🤗 Optimum is an extension of Transformers that provides a set of performance optimization tools to train and run models on targeted hardware with maximum efficiency.
    The AI ecosystem evolves quickly, and more and more specialized hardware along with their own optimizations are emerging every day. 
    As such, Optimum enables developers to efficiently use any of these platforms with the same ease inherent to Transformers.
  doc_url: https://huggingface.co/docs/optimum/index
  dev_url: https://github.com/huggingface/optimum

extra:
  recipe-maintainers:
    - sugatoray
